### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [jonniebigodes/design-systems-with-gh-actions#12]
It has been noticed that while using chromaui/action@v1 your projectToken d7pka2o3z65 is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by jonniebigodes** [comment]
@raima-zachariah as I've mentioned in the other issue. I'm aware of this. This repo is intended to be a demonstration one. Its days are numbered as most of this code/content is a bit outdated.

Thank you nonetheless for letting me know

**Comment by raima-zachariah** [comment]
Thanks for taking the time to respond. I was working on a vulnerability analysis and this was part of my report. Thanks for letting me know the intent behind.

**Comment by jonniebigodes** [comment]
@raima-zachariah no need to thank whatsoever. Good luck with the vulnerability analysis that you're working on. Please let us know of any further issues related to Storybook either in the LearnStorybook [repo](https://github.com/chromaui/learnstorybook.com) for anything related to the tutorials or in the official Storybook [repo](https://github.com/storybookjs/storybook) for issues related to Storybook. For questions/issues related to [Chromatic](https://www.chromatic.com/) itself feel free to chat with the team. We're more than welcome to answer each and every question you might have.

If you don't mind I'm going to close this issue.


Stay safe
